Board.ApplicationSerializer = DS.LSSerializer.extend();
Board.ApplicationAdapter = DS.LSAdapter.extend();

// var posts = [
// { id: '1',
// title: "Try-hard lumbersexual semiotics",
// body: "Try-hard lumbersexual semiotics four loko gastropub, pug put a bird on it. Jean shorts freegan +1 Tumblr, cronut fanny pack letterpress kogi distillery YOLO cardigan fingerstache. Literally dreamcatcher lo-fi kale chips vegan. Scenester health goth small batch, McSweeney's Marfa Tumblr seitan Helvetica tousled meh wolf. Occupy +1 8-bit ethical, Godard VHS wayfarers mustache.Intelligentsia Blue Bottle farm-to-table small batch bespoke, jean shorts roof party kitsch ethical brunch salvia Etsy Vice actually freegan. Cray hella asymmetrical, tousled McSweeney's cardigan farm-to-table mumblecore cronut Austin normcore.Butcher sartorial Pitchfork, trust fund Portland gastropub authentic cray fashion axe. Tumblr lomo health goth, tilde pickled fashion axe retro readymade. Fanny pack taxidermy kogi lumbersexual, paleo food truck crucifix before they sold out semiotics typewriter. Mustache actually lomo authentic, blog pour-over Banksy. Stumptown +1 before they sold out 8-bit. Heirloom single-origin coffee Vice, swag Pinterest hoodie cardigan cronut paleo gluten-free deep v roof party bespoke typewriter. Readymade PBR letterpress heirloom.Etsy asymmetrical gentrify aesthetic gluten-free. Tousled 90's PBR&B narwhal, trust fund Odd Future freegan seitan before they sold out brunch. Master cleanse food truck flexitarian readymade. Gluten-free meh single-origin coffee, asymmetrical cronut church-key ethical +1 selvage umami. Cardigan Intelligentsia Pinterest, actually bespoke fanny pack trust fund farm-t3o-table. Typewriter Intelligentsia semiotics High Life whatever fingerstache, master cleanse Pitchfork kogi Etsy viral. Beard Neutra ugh, jean shorts hoodie church-key hella umami." },
//
// { id: '2',
// title: "3 wolf moon mumblecore ",
// body: "Food truck roof party Neutra PBR lumbersexual deep v, gluten-free readymade locavore selvage Wes Anderson dreamcatcher. Godard sartorial master cleanse tousled, cliche small batch selfies trust fund lo-fi wayfarers flannel letterpress cray. Typewriter next level 90's squid, Vice Intelligentsia health goth farm-to-table Godard readymade lumbersexual twee lo-fi viral. Pop-up PBR&B gastropub fashion axe, dreamcatcher beard banjo. Meggings fingerstache meh, lo-fi distillery Blue Bottle salvia. Try-hard YOLO four loko, Portland art party drinking vinegar pour-over meggings hashtag kitsch crucifix organic jean shorts hoodie Carles. Post-ironic pug actually Banksy, mixtape mumblecore put a bird on it try-hard gastropub normcore McSweeney's letterpress dreamcatcher drinking vinegar. Forage fap single-origin coffee, shabby chic bitters mixtape lo-fi leggings Neutra pour-over scenester roof party seitan Etsy taxidermy. Forage fixie paleo, YOLO locavore 90's twee mlkshk meditation small batch synth. Meggings crucifix ugh, swag fashion axe Blue Bottle biodiesel paleo small batch trust fund beard slow-carb flannel selvage scenester. Butcher Austin you probably haven't heard of them raw denim. Chillwave slow-carb selvage vegan. Squid tilde Neutra, salvia artisan before they sold out cray authentic flannel Bushwick beard lo-fi Truffaut. Taxidermy letterpress crucifix pop-up, cold-pressed before they sold out hella skateboard disrupt shabby chic selvage kale chips.Tattooed Thundercats fashion axe, Pitchfork keytar gastropub normcore American Apparel mixtape jean shorts. Distillery gentrify photo booth hashtag. Kitsch heirloom before they sold out bitters pop-up. Health goth fingerstache skateboard aesthetic Vice ugh artisan farm-to-table, pug vinyl fap craft beer pour-over. Pour-over DIY 8-bit, gastropub kitsch meggings ennui beard 3 wolf moon mumblecore actually crucifix drinking vinegar yr plaid. Art party salvia McSweeney's, banh mi Godard chia wolf gluten-free gentrify iPhone. Asymmetrical sriracha irony PBR, cred actually plaid hella Banksy Odd Future letterpress Intelligentsia seitan." },
//
// { id: '3',
// title: "IPhone four loko kitsch ",
// body: "Etsy XOXO bicycle rights, pickled mustache post-ironic kitsch single-origin coffee PBR&B. IPhone four loko kitsch forage swag letterpress, Odd Future bespoke cardigan squid listicle artisan synth. Slow-carb squid flexitarian, Intelligentsia dreamcatcher hella semiotics deep v hashtag. Quinoa Wes Anderson post-ironic, raw denim dreamcatcher literally four loko cray Brooklyn bicycle rights next level. Seitan cronut ennui, XOXO next level artisan kitsch yr fingerstache mixtape pop-up sustainable four dollar toast selvage flannel. Pork belly XOXO synth listicle deep v. Occupy cray lo-fi, wayfarers shabby chic keffiyeh selvage Intelligentsia lomo umami vegan master cleanse Helvetica. Banh mi PBR&B hella chillwave, 3 wolf moon disrupt brunch shabby chic Vice American Apparel stumptown mixtape. McSweeney's Austin pug, roof party scenester butcher tofu. Portland twee readymade irony fap before they sold out, street art cray Banksy chillwave DIY try-hard. Trust fund DIY kitsch tofu swag American Apparel, tattooed cray Kickstarter typewriter lumbersexual four loko PBR viral Helvetica. Tumblr pug lo-fi gentrify drinking vinegar iPhone disrupt, Blue Bottle forage before they sold out taxidermy. VHS Odd Future four dollar toast, chillwave swag cronut Tumblr. Polaroid PBR beard forage.Cornhole food truck chillwave, American Apparel Echo Park Brooklyn artisan leggings taxidermy brunch hella shabby chic four loko. Semiotics chia fanny pack, blog retro YOLO trust fund raw denim cardigan gastropub. Small batch brunch normcore Blue Bottle mixtape, pickled American Apparel biodiesel cliche put a bird on it art party master cleanse. Crucifix mumblecore tattooed selvage swag before they sold out. Craft beer pour-over PBR Austin Godard biodiesel. Thundercats small batch forage farm-to-table authentic Blue Bottle deep v single-origin coffee. Meditation mumblecore gluten-free heirloom Shoreditch. Oh. You need a little dummy text for your mockup? How quaint." },
//
// { id: '4',
// title: "8-bit fixie. ",
// body: "Deep v meditation hella asymmetrical, squid tattooed cold-pressed. Austin hashtag gastropub, keffiyeh paleo Truffaut Wes Anderson. Meh sustainable selfies plaid tattooed, typewriter fixie. Portland sustainable fap taxidermy cray, stumptown hoodie keytar cold-pressed. IPhone polaroid fap flannel chillwave, DIY Williamsburg Intelligentsia salvia letterpress seitan McSweeney's leggings mustache pork belly. Fap flannel Pitchfork Pinterest, slow-carb messenger bag Neutra. +1 street art mixtape Banksy dreamcatcher banjo farm-to-table Etsy bespoke Intelligentsia, bicycle rights meggings VHS. Yr banjo artisan, keffiyeh mlkshk letterpress Austin meh tousled keytar actually selfies twee kogi sustainable. Hoodie flannel pour-over, ennui dreamcatcher 8-bit kogi post-ironic actually YOLO synth Etsy. Dreamcatcher butcher put a bird on it, art party Wes Anderson crucifix Vice you probably haven't heard of them slow-carb Odd Future selfies pop-up mumblecore bicycle rights. Irony gastropub slow-carb try-hard paleo. Keffiyeh locavore pour-over squid small batch quinoa, deep v iPhone put a bird on it seitan drinking vinegar. Umami Williamsburg listicle roof party. DIY ennui umami, narwhal fap Marfa irony chia flexitarian freegan church-key viral whatever. +1 meh Intelligentsia single-origin coffee small batch actually pop-up, meditation American Apparel street art direct trade 8-bit fixie. Chambray cornhole seitan tilde Bushwick plaid. Cardigan stumptown iPhone 8-bit, 3 wolf moon VHS literally pork belly. Twee tattooed ugh iPhone, salvia you probably haven't heard of them whatever kogi food truck health goth synth forage. Freegan skateboard twee tote bag, flexitarian Godard Austin typewriter Portland DIY cred. Umami PBR&B jean shorts normcore leggings. Chambray Austin food truck flexitarian normcore, bespoke tattooed Portland DIY Shoreditch gluten-free 3 wolf moon sustainable viral tote bag." }
// ];
//
// var comments = [ { id: '1', postId: '3', text: 'What a shame!' }, { id: '2', postId: '3', text: 'I am so sorry. How are you feeling now?' }, { id: '3', postId: '1', text: 'I love blodd too!' } ];
